const data = [
    {
      id: 1,
      ciudad: "ALMERÍA",
      pais: "ESPAÑA",
      humedad: 50,
      gradosc: 28,
      gradosf: 82,
      viento: "11 mph",
      cielo: "SOLEADO",
    },
    {
      id: 2,
      ciudad: "PAMPLONA",
      pais: "ESPAÑA",
      humedad: 55,
      gradosc: 23,
      gradosf: 73,
      viento: "9 mph",
      cielo: "NUBLADO",
    },
    {
      id: 3,
      ciudad: "SANTANDER",
      pais: "ESPAÑA",
      humedad: 70,
      gradosc: 20,
      gradosf: 68,
      viento: "12 mph",
      cielo: "LLUVIA",
    },
    {
      id: 4,
      ciudad: "TOLEDO",
      pais: "ESPAÑA",
      humedad: 40,
      gradosc: 30,
      gradosf: 86,
      viento: "13 mph",
      cielo: "SOLEADO",
    },
    {
      id: 5,
      ciudad: "SORIA",
      pais: "ESPAÑA",
      humedad: 60,
      gradosc: 22,
      gradosf: 72,
      viento: "8 mph",
      cielo: "NUBLADO",
    },
    {
      id: 6,
      ciudad: "HUELVA",
      pais: "ESPAÑA",
      humedad: 60,
      gradosc: 26,
      gradosf: 79,
      viento: "10 mph",
      cielo: "SOLEADO",
    },
    {
      id: 7,
      ciudad: "SALAMANCA",
      pais: "ESPAÑA",
      humedad: 50,
      gradosc: 24,
      gradosf: 75,
      viento: "9 mph",
      cielo: "LLUVIA",
    },
    {
      id: 8,
      ciudad: "BADAJOZ",
      pais: "ESPAÑA",
      humedad: 45,
      gradosc: 31,
      gradosf: 88,
      viento: "11 mph",
      cielo: "SOLEADO",
    },
    {
      id: 9,
      ciudad: "CÁDIZ",
      pais: "ESPAÑA",
      humedad: 65,
      gradosc: 27,
      gradosf: 81,
      viento: "12 mph",
      cielo: "SOLEADO",
    },
    {
      id: 10,
      ciudad: "LEÓN",
      pais: "ESPAÑA",
      humedad: 55,
      gradosc: 22,
      gradosf: 72,
      viento: "10 mph",
      cielo: "NUBLADO",
    },
  ];

  const jsonData = JSON.stringify(data)

  export default jsonData;
